spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "@db.url@"
    username: "@db.username@"
    password: "@db.password@"
  redis:
    host: "@redis.host@"
    port: "@redis.port@"
    password: "@redis.password@"
    lettuce:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1ms
logging:
  file:
    path: /home/logs/easyboot

app:
  storage:
    enable: "@storage.enable@"
    type: "@storage.type@"
    ak: "@storage.ak@"
    sk: "@storage.sk@"
    bucket: "@storage.bucket@"
    domain: "@storage.domain@"
