spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.212.5:53306/easyboot
    username: root
    password: Root123$%^
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1ms

app:
  storage:
    enable: true
    type: qiniu
    ak: k-UME1JQRAaNaOcbKJXe24KusyPayaYp-ZLDkA6U
    sk: H4rhmlI6sX69sy2DGrdUOVlWe_ERSIDmyTDBUgi1
    bucket: developer
    domain: http://dev.static.codehu.net