spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/easyboot?serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 1
        max-idle: 8
        max-active: 8
        max-wait: -1ms

app:
  storage:
    enable: true
    type: qiniu
    ak: your ak
    sk: your sk
    bucket: your bucket
    domain: your domain